
messages:
  buildmsg: '&4can not build on OWNER land'
  breakmsg: '&4can not break on OWNER land'
  usemsg: '&4can not use CONTAINER on OWNER land'
  emptybucket: '&4can not empty buckets on OWNER land'
  fillbucket: '&4can not fill buckets on OWNER land'
  pets: '&4that THEPET belongs to OWNER'
  pvpoff: '&4you can not kill OWNER on his land'
  breakframe: '&4can not break item frame in OWNER land'
  putframe: '&4can not put frames on OWNER land'
  moveframe: '&4can not move items in frames on OWNER land'
  getframe: '&4can not get the item in that frame belongs to OWNER land'
  armorstand: '&4that armor belongs to OWNER'
  breakstand: '&4can not break that armor stand belongs to OWNER'
  defaultenter: '&aEntering OWNER land'
  defaultleave: '&aLeaving OWNER land'
  reachlimitchunk: '&4PLAYER you have reach the max amount of chunks'
  teleportmsg: '&bteleporting to LOCATION'
