name: Landlord
main: com.craftilandia.chunkprotector.Main
version: 17.0
author: raton023
website: http://dev.bukkit.org/bukkit-plugins/blockguard/
softdepend: [Vault]
commands:
    landclaim:
        description: Claim Land.
        usage: /landclaim <landname> ej. /landclaim spawn
    landunclaim:
        description: Unclaim a Land.
        usage: /landunclaim <landname> ej. /landunclaim spawn
    landallow:
        description: Add a friend to your lands.
        usage: /landallow <playername> ej. /landallow raton023
    landallowlist:
        description: See your friends list.
        usage: /landallowlist <player> ej. /landallowlist raton023
    landlist:
        description: See a player land list.
        usage: /landlist <playername> ej. /landlist raton023
    landtp:
        description: Teleport to a land.
        usage: /landtp <landname> ej. /landtp spawn
    landtpset:
        description: Set the teleport to where you stand.
        usage: /landtpset <landname> ej. /landtpset spawn
    landgive:
        description: Give a land to a player.
        usage: /landgive <landname> <player> ej. /landtp spawn raton023
    landdisallow:
        description: Remove a friend from your lands.
        usage: /landdisallow <player> ej. /landdisallow raton023
    landenter:
        description: Change the welcome message of your land.
        usage: /landenter <landname> <message> ej. /landenter spawn &aWelcome to the Spawn.
    landexit:
        description: Change the leaving message of your land.
        usage: /landenter <landname> <message> ej. /landenter spawn &aLeaving Spawn.
    landtax:
        description: Charge landlords.
        usage: /landtax
permissions:
    chunkprotector.unlimited:
        description: To have unlimited chunks claims.
        default: op
    chunkprotector.admin:
        description: To run commands as another players(working on this).
        default: false
    chunkprotector.bypass:
        description: to bypass all the protections.
        default: op
    chunkprotector.3:
        description: how many chunks a player can register.
        default: true
    chunkprotector.nobuild:
        description: if player can not build outside of a registered chunk.
        default: false
    chunkprotector.nobreak:
        description: if player can not break outside of a registered chunk.
        default: false
    chunkprotector.nopay:
        description: if player have this he will not pay for taxes or claim costs.
        default: op
